### ISSUE TITLE
Update please <3

### ISSUE THREAD

**Issue by Suburbanno** [Cypher01/Xglyph2#6]

**Comment by Cypher01** [comment]
Hm? What do you mean?

**Comment by Suburbanno** [comment]
Hey!! @Cypher01 , Upgrade to the new version of Ingress, and you could do a "human" mode where it would simulate human speeds, ex: 85%/75%% 50%?

**Comment by Cypher01** [comment]
Xglyph² v1.6.1 is still compatible with the actual Ingress v1.126.0.

You should do your best to draw the glyphs right, not just tapping the screen. So a "human" mode is not necessary.

You also shouldn't use Xglyph² permanently, it's cheaty!
