### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Fastidio96** [Cypher01/Xglyph2#7]
This version not working with actual version of ingress(1.31.1).
Any update?

**Comment by Cypher01** [comment]
The module works with the current Ingress version 1.131.2
What device and Rom do you use? Do you see any errors/warnings when you open Xglyph²? Do other Xposed modules work?
Take a look at the FAQ at the thread on XDA.
https://forum.xda-developers.com/xposed/modules/mod-xglyph-ingress-glyph-game-mods-t3455025
