### ISSUE TITLE
Ingress Prime

### ISSUE THREAD

**Issue by SessePrime** [Cypher01/Xglyph2#8]

**Comment by Cypher01** [comment]
I'm afraid Xglyph² will die with the introduction of Ingress Prime.
Ingress Prime is based on the Unity graphics engine. Unity code compiles to native machine code, which is not hookable by Xposed. If the glyph related code is part of this, the approach used by Xglyph² will not work anymore.
Additionally there are rumours that Ingress Prime introduces Google SafetyNet. In this case we would end up in the same situation as with Pokemon Go, which refuses to start on devices running Xposed. I hope that this is not true.
We will see. I don't have access to Ingress Prime yet. When I have the chance to take a look at the apk, I can tell more. Be sure to follow the thread on XDA.
https://forum.xda-developers.com/xposed/modules/mod-xglyph-ingress-glyph-game-mods-t3455025

**Comment by SessePrime** [comment]
Thanks a lot, sir.
Your Xglyph2 has made my days a lot of times helping me to reach 5 accounts to level 10.
Still working fine.
You are my xposed hero.
Have a good day.

By the way, IngressPrime is available now on Google play.
Thank you.

**Comment by Cypher01** [comment]
Thx. :-)

Oh, I didn't realize that Ingress Prime is already available for everyone. Obviously started just a few hours ago.

**Comment by Cypher01** [comment]
I added a section about Compatibility to the first post on XDA, be sure to check it out.
https://forum.xda-developers.com/xposed/modules/mod-xglyph-ingress-glyph-game-mods-t3455025
